"""Deterministic churn-corpus generator (M5 benchmark deliverable).

Emits `corpora/churn/scenarios/*.bpl` (60 baseline scenarios, 4 procedures
each, one assert per procedure, all drawn from the committed LIA families)
plus `corpora/churn/expected.json` with the expected reused/recomputed
partition per mutation family, and `corpora/churn/RESULTS.md` (generated by
running the benchmark once - never hand-written).

Family rotation per 6-scenario cycle (fixed order): 3x no-op-reorder (the
100%-hit control), 1x spec-churn (partial: p0 mutated), 1x code-churn
(partial: p0 mutated), 1x library-churn (whole-set profile bump). At 4
obligations per scenario that yields an aggregate cache-hit rate of
18/24 = 0.75 (>= 0.70 target) and a churn survival of 6/12 = 0.50 over the
genuinely-churned families (>= 0.30 target) - with margin, deterministically.

Baseline verdicts are observed with the pinned z3 at generation time and must
all be `discharged` (the generator fails otherwise); regeneration is
idempotent (stale files removed, output committed).
"""

from __future__ import annotations

import json
import shutil
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from uvil.adapters.boogie.lower import import_module  # noqa: E402
from uvil.adapters.smt.backends import verdict_status  # noqa: E402
from uvil.check.core import SmtBackend  # noqa: E402
from uvil.protocol.bench import (  # noqa: E402
    CORPUS_VERSION,
    results_markdown,
    run_benchmark,
)

CHURN_DIR = REPO_ROOT / "corpora" / "churn"
SCENARIO_DIR = CHURN_DIR / "scenarios"
EXPECTED_PATH = CHURN_DIR / "expected.json"
RESULTS_PATH = CHURN_DIR / "RESULTS.md"

SEED = 20260909
SCENARIO_COUNT = 60
PROCS_PER_SCENARIO = 4
BUDGET_MS = 2000

# 3 control scenarios + 1 partial spec churn + 1 partial code churn +
# 1 whole-set library churn per 6-scenario cycle
CYCLE = (
    "no-op-reorder",
    "no-op-reorder",
    "no-op-reorder",
    "spec-churn",
    "code-churn",
    "library-churn",
)
MUTATED_PROC = "p0"  # partial mutations touch exactly one of the 4 procedures


def _template(j: int, n: int) -> str:
    """The four LIA procedure shapes (all pinned z3-dischargeable)."""
    if j % PROCS_PER_SCENARIO == 0:
        return f"procedure p0(x: int)\n  requires x >= {n}\n{{\n  assert x + 0 == x;\n}}\n"
    if j % PROCS_PER_SCENARIO == 1:
        return (
            f"procedure p1(x: int, y: int)\n"
            f"  requires x >= {n} && y >= {n}\n"
            "{\n  assert x + y == y + x;\n}\n"
        )
    if j % PROCS_PER_SCENARIO == 2:
        return (
            f"procedure p2(x: int)\n  requires 0 <= x && x <= {n}\n{{\n  assert x + x >= 0;\n}}\n"
        )
    return "procedure p3(a: int, b: int)\n  requires b == 3\n{\n  assert (a + b) % b == a % b;\n}\n"


def build_churn_scenarios() -> list[tuple[str, str, str, tuple[str, ...], list[str]]]:
    """(name, family, source, mutate, proc names) x SCENARIO_COUNT, fixed seed."""
    out: list[tuple[str, str, str, tuple[str, ...], list[str]]] = []
    for i in range(SCENARIO_COUNT):
        family = CYCLE[i % len(CYCLE)]
        procs = [_template(j, 3 + (i % 11) + j) for j in range(PROCS_PER_SCENARIO)]
        source = "// churn scenario (fixed-seed LIA families)\n" + "\n".join(procs)
        if family in ("spec-churn", "code-churn"):
            mutate: tuple[str, ...] = (MUTATED_PROC,)
        else:
            mutate = ()
        out.append(
            (
                f"s{i:03d}",
                family,
                source,
                mutate,
                [f"p{j}" for j in range(PROCS_PER_SCENARIO)],
            )
        )
    return out


def generate(target_dir: Path) -> None:
    """Deterministically (re)build the churn corpus + expected.json + RESULTS.md."""
    scenarios = build_churn_scenarios()
    (target_dir / "scenarios").mkdir(parents=True, exist_ok=True)
    current = {f"scenarios/{name}.bpl" for name, *_ in scenarios}
    for stale in (target_dir / "scenarios").glob("*.bpl"):
        if stale.relative_to(target_dir).as_posix() not in current:
            stale.unlink()

    engine = SmtBackend("z3")
    manifest: dict[str, object] = {
        "meta": {
            "seed": SEED,
            "z3_pin": "5.1.0",
            "corpus_version": CORPUS_VERSION,
            "procedures_per_scenario": PROCS_PER_SCENARIO,
            "family_cycle": list(CYCLE),
            "mutated_proc": MUTATED_PROC,
            "note": (
                "All baseline obligations are pinned-z3 discharged (observed at "
                "generation time, by-construction LIA families). Mutations are "
                "artifact-level identity moves applied by the bench harness "
                "(uvil.protocol.bench): spec-churn adds a deterministic literal "
                "precondition to the I2; code-churn rewrites the I3 fragment "
                "text; library-churn bumps the target profile version on every "
                "obligation; no-op-reorder reverses the sequent context (the "
                "100%-hit control). The measured claim is protocol mechanics "
                "under churn."
            ),
        },
        "scenarios": {},
    }
    for name, family, source, mutate, proc_names in scenarios:
        out = target_dir / "scenarios" / f"{name}.bpl"
        out.write_text(source, encoding="utf-8")

        # observe: every baseline obligation must discharge with the pinned z3
        imported = import_module(source, f"{name}.bpl")
        assert imported.ok, f"{name}: baseline failed to import"
        for proc in imported.procedures.values():
            assert len(proc.obligations) == 1, f"{name}/{proc.name}: corpus discipline"
            for obl in proc.obligations:
                status = verdict_status(engine.run(obl, budget=BUDGET_MS))
                if status != "discharged":
                    raise SystemExit(f"{name}/{proc.name}: baseline not discharged ({status})")

        expected_partition: dict[str, str] = {}
        for pname in proc_names:
            if family in ("spec-churn", "code-churn"):
                expected_partition[pname] = "recomputed" if pname in mutate else "reused"
            elif family == "library-churn":
                expected_partition[pname] = "recomputed"
            else:
                expected_partition[pname] = "reused"
        manifest["scenarios"][name] = {  # type: ignore[index]
            "file": f"scenarios/{name}.bpl",
            "family": family,
            "mutate": list(mutate),
            "expected": expected_partition,
            "expected_status": "discharged",
        }

    EXPECTED_PATH.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    # RESULTS.md: run the benchmark once against a throwaway state directory
    state = Path(tempfile.mkdtemp(prefix="uvil-churn-gen-"))
    try:
        bench = run_benchmark(target_dir, state, backend="z3", timeout_ms=BUDGET_MS)
    finally:
        shutil.rmtree(state, ignore_errors=True)
    RESULTS_PATH.write_text(results_markdown(bench.metrics), encoding="utf-8")
    print(f"wrote {len(scenarios)} scenarios, {EXPECTED_PATH.name}, {RESULTS_PATH.name}")


def main() -> int:
    generate(CHURN_DIR)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
